#ifndef MPA_MPABASE_INTERFACE_INCLUDE_MPAINTERFACEGLOBAL_H_
#define MPA_MPABASE_INTERFACE_INCLUDE_MPAINTERFACEGLOBAL_H_

#ifdef _WIN32
#ifdef MPA_BUILD_INTERFACE_LIB
#define MPA_INTERFACE_EXPORT __declspec(dllexport)
#else
#define MPA_INTERFACE_EXPORT __declspec(dllimport)
#endif
#else
#define MPA_INTERFACE_EXPORT
#endif

#endif  // MPA_MPABASE_INTERFACE_INCLUDE_MPAINTERFACEGLOBAL_H_
